## YAML Template.
user_new:
    path:    /new
    defaults: { _controller: "AppBundle:User:new"}
    methods: POST

user_upload_image:
    path:    /upload-image-user
    defaults: { _controller: "AppBundle:User:uploadImage"}
    methods: POST